server:
  port: 8088
  servlet:
    context-path: /TSM
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: project
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #mysql?????
    #url: jdbc:mysql://127.0.0.1:3308/mydb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: root2020
    #driver-class-name: com.mysql.cj.jdbc.Driver
    # ??druid???
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # ????????
      validationQuery: SELECT 1 FROM DUAL
      # ???????????
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # ??????????????????????
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # ??PSCache??????????PSCache???
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      # ?????????filters????????sql?????'wall'?????
      filters: stat,wall
#????
# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #逻辑删除列
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


